### ISSUE TITLE
Failed Tests

### ISSUE THREAD

**Issue by poornagurram** [domokane/FinancePy#44]
runAllTests.py raises error while testing the master. only two test cases passed. Need to add functionality to check other tests instead of halting if one test fails too.
```
Testing module TestFinModelRatesBDT (3 out of 90)
Traceback (most recent call last):
  File "tests/runAllTests.py", line 26, in <module>
    moduleName = __import__(moduleTextName)
  File "/home/runner/work/FinancePy/FinancePy/tests/TestFinModelRatesBDT.py", line 284, in <module>
    test_BDTExampleTwo()
  File "/home/runner/work/FinancePy/FinancePy/tests/TestFinModelRatesBDT.py", line 160, in test_BDTExampleTwo
    price = bond.cleanPriceFromDiscountCurve(settlementDate, curve)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/financepy-0.184-py3.8.egg/financepy/products/bonds/FinBond.py", line 320, in cleanPriceFromDiscountCurve
    self.calcAccruedInterest(settlementDate)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/financepy-0.184-py3.8.egg/financepy/products/bonds/FinBond.py", line 443, in calcAccruedInterest
    (accFactor, num, _) = dc.yearFrac(self._pcd,
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/financepy-0.184-py3.8.egg/financepy/finutils/FinDayCount.py", line 213, in yearFrac
    freq = FinFrequency(frequencyType)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/financepy-0.184-py3.8.egg/financepy/finutils/FinFrequency.py", line 30, in FinFrequency
    if frequencyType in FinFrequencyTypes:
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/enum.py", line 315, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumMeta'
```

**Comment by poornagurram** [comment]
Fixed
